### ISSUE TITLE
Composer require fetches wrong version

### ISSUE THREAD

**Issue by PunchRockgroin** [bradcornford/Bootstrapper#27]
When installing using "cornford/bootstrapper": "2.*", the version fetched is old. You can tell first because L5 fails out with "Call to undefined method [package]" and the jQuery version is old at 2.1.1

Using "cornford/bootstrapper": "dev-master" fetches the latest version.

**Comment by bradcornford** [comment]
I'm not entirely sure what had happened, my local version seemed to have lost version two tags. I've reset to the remote version, and re-tagged.
