### ISSUE TITLE
Update for 5.4: Replace Illuminate\Html with Collective\Html

### ISSUE THREAD

**Issue by PunchRockgroin** [bradcornford/Bootstrapper#30]
Primarily because Illuminate\Html\FormBuilder uses $this->app->bindShared and Session->getToken(), both of which are depreciated and have been removed in 5.4

This also means the BootstrapServiceProvider call to $app['session.store']->getToken() should be changed to $app['session.store']->token() on line 35.

Hopefully Collective\Html ends up being a drop-in replacement. I'm testing it out on my own fork to see if I run into any more 5.4 update issues.

**Comment by bradcornford** [comment]
Hi there,

I'll look at implementing this soon. Let me know how running it on your own fork works. If it's good feel free to drop a pull request in.

**Comment by jitopdeveloper** [comment]
i got this error

> Class 'Cornford\Bootstrapper\Facades\Bootstrap' not found (View:

**Comment by bradcornford** [comment]
Fixed in version current version 2.6.0.
